blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation Copier
    url: https://copier.readthedocs.io/
    about: Official Copier documentation
  - name: 💬 Discussions
    url: https://github.com/rlhoussaine/python-template/discussions
    about: General questions and experience sharing
